//
//  SKDataBase.swift
//  Comedie
//
//  Created by Zignuts Technolab on 10/05/18.
//  Copyright © 2018 Zignuts Technolab. All rights reserved.
//

import Foundation

enum SKDataKeys: String {
    
    //Login Param
    case address = "address"
    case address_gj = "address_gj"
    case area = "area"
    case area_gj = "area_gj"
    case birthdate = "birthdate"
    case blood_group = "blood_group"
    case business_type_id = "business_type_id"
    case business_type_id_gj = "business_type_id_gj"
    case business_type_name = "business_type_name"
    case business_type_name_gj = "business_type_name_gj"
    case city = "city"
    case city_gj = "city_gj"
    case city_id = "city_id"
    case city_id_gj = "city_id_gj"
    case company_address = "company_address"
    case company_address_gj = "company_address_gj"
    case company_name = "company_name"
    case company_name_gj = "company_name_gj"
    case company_phone = "company_phone"
    case country = "country"
    case country_code = "country_code"
    case country_gj = "country_gj"
    case country_id = "country_id"
    case country_id_gj = "country_id_gj"
    case eduction = "eduction"
    case eduction_gj = "eduction_gj"
    case email = "email"
    case first_name = "first_name"
    case first_name_gj = "first_name_gj"
    case gender = "gender"
    case hobbies = "hobbies"
    case hobbies_gj = "hobbies_gj"
    case last_name = "last_name"
    case last_name_gj = "last_name_gj"
    case marital_status = "marital_status"
    case marital_status_gj = "marital_status_gj"
    case membership_no = "membership_no"
    case middle_name = "middle_name"
    case middle_name_gj = "middle_name_gj"
    case mobile = "mobile"
    case other_business_type_name = "other_business_type_name"
    case other_business_type_name_gj = "other_business_type_name_gj"
    case parent_id = "parent_id"
    case pincode = "pincode"
    case pole_id = "pole_id"
    case pole_id_gj = "pole_id_gj"
    case pole_name = "pole_name"
    case pole_name_gj = "pole_name_gj"
    case position = "position"
    case position_gj = "position_gj"
    case previous_saakh = "previous_saakh"
    case previous_saakh_gj = "previous_saakh_gj"
    case previous_saakh_id = "previous_saakh_id"
    case previous_saakh_id_gj = "previous_saakh_id_gj"
    case profession_id = "profession_id"
    case profession_id_gj = "profession_id_gj"
    case profession_name = "profession_name"
    case profession_name_gj = "profession_name_gj"
    case profile_picture = "profile_picture"
    case reference = "reference"
    case relation = "relation"
    case relation_gj = "relation_gj"
    case saakh = "saakh"
    case saakh_id = "saakh_id"
    case saakh_id_gj = "saakh_id_gj"
    case saakh_name_gj = "saakh_name_gj"
    case status = "status"
    case telephone = "telephone"
    case token_id = "token_id"
    case user_id = "user_id"
    case user_roll_id = "user_roll_id"
    case username = "username"
    case password = "password"
    case confirm_password = "confirm_password"
    case currentPassword = "currentPassword"
    case contact = "contact"
    case mother_name = "mother_name"
    case mother_name_gj = "mother_name_gj"
    case current_address = "current_address"
    case current_address_gj = "current_address_gj"
    case mobile_guardian = "mobile_guardian"
    case birth_date = "birth_date"
    case birth_time = "birth_time"
    case mangal_shani = "mangal_shani"
    case birth_place = "birth_place"
    case birth_place_gj = "birth_place_gj"
    case height = "height"
    case weight = "weight"
    case complexion = "complexion"
    case complexion_gj = "complexion_gj"
    case horoscope = "horoscope"
    case groom_bride_preferences = "groom_bride_preferences"
    case groom_bride_preferences_gj = "groom_bride_preferences_gj"
    case qualification = "qualification"
    case qualification_gj = "qualification_gj"
    case any_deficiency = "any_deficiency"
    case any_deficiency_gj = "any_deficiency_gj"
    case current_activity = "current_activity"
    case current_activity_gj = "current_activity_gj"
    case glasses_is = "glasses_is"
    case house = "house"
    case annual_income = "annual_income"
    case annual_income_family = "annual_income_family"
    case occupation_father = "occupation_father"
    case occupation_mother = "occupation_mother"
    case many_brothers = "many_brothers"
    case many_sisters = "many_sisters"
    case married_brothers = "married_brothers"
    case married_sisters = "married_sisters"
    case janmakshar = "janmakshar"
    case requirement = "requirement"
    case mosad_details = "mosad_details"
    case photo = "photo"
    case photo_2 = "photo_2"
    case family_member_id = "family_member_id"
    case witness_name = "witness_name"
    
    case name = "name"
    
}



